steps:
  # ---------- Build Docker Image ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:latest",
        "-f", "myapp/Dockerfile",
        "myapp/"
      ]

  # ---------- Push to Artifact Registry ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:latest"
      ]

  # 🚀 ---------- AUTHENTICATE AND DEPLOY (Consolidated Step) ----------
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        # 1. GKE Auth
        "gcloud container clusters get-credentials gitlab-gke --zone asia-south1-c --project s-0-009988 && "

        # 2. Replace image tag: ***FIXED to use :latest tag***
        "sed -i \"s#IMAGE_PLACEHOLDER#asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:latest#g\" myapp/deployment.yaml && "

        # 3. Configure Docker (This step is technically redundant in Cloud Build but harmless)
        "gcloud auth configure-docker asia-south1-docker.pkg.dev && "
        
        # 4. Apply Kubernetes manifests
        "kubectl apply -f myapp/deployment.yaml --namespace default && "

        # 5. Wait for rollout
        "kubectl rollout status -f myapp/deployment.yaml --namespace default"
      ]
      
options:
  logging: CLOUD_LOGGING_ONLY
