steps:
  # ---------- Build Docker Image ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:$COMMIT_SHA",
        "-f", "myapp/Dockerfile",
        "myapp/"
      ]

  # ---------- Push to Artifact Registry ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:$COMMIT_SHA"
      ]

# ---------- Authenticate to GKE (Kubeconfig is written to /root/.kube/config) ----------
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "container", "clusters", "get-credentials",
        "gitlab-gke",
        "--zone", "asia-south1-c",
        "--project", "s-0-009988"
      ]
    # The GKE config is written to /root/.kube/config inside this container
    volumes:
      - name: kube
        path: /root/.kube # The shared volume# ... (Steps 1 & 2 are correct)

  # ---------- Authenticate to GKE (Kubeconfig is written to /root/.kube/config) ----------
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "container", "clusters", "get-credentials",
        "gitlab-gke",
        "--zone", "asia-south1-c",
        "--project", "s-0-009988"
      ]
    # The GKE config is written to /root/.kube/config inside this container
    volumes:
      - name: kube
        path: /root/.kube # The shared volume

  # ---------- Replace image tag inside YAML (Requires KUBECONFIG for later steps) ----------
  # No change to this step, but it must precede the kubectl steps.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        "sed -i \"s#IMAGE_PLACEHOLDER#asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:${COMMIT_SHA}#g\" myapp/deployment.yaml"
      ]
    volumes:
      - name: kube
        path: /root/.kube

  # ---------- Apply Kubernetes manifests (KUBECONFIG is key here) ----------
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "apply",
        "-f", "myapp/deployment.yaml",
        "--namespace", "default"
      ]
    volumes:
      - name: kube
        path: /root/.kube
    # **Add the KUBECONFIG environment variable**
    env:
      - 'KUBECONFIG=/root/.kube/config' # Explicitly tells kubectl where to find the credentials

  # ---------- Wait for rollout (KUBECONFIG is key here) ----------
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "rollout", "status",
        "-f", "myapp/deployment.yaml",
        "--namespace", "default"
      ]
    volumes:
      - name: kube
        path: /root/.kube
    # **Add the KUBECONFIG environment variable**
    env:
      - 'KUBECONFIG=/root/.kube/config' # Explicitly tells kubectl where to find the credentials
      
options:
  logging: CLOUD_LOGGING_ONLY
