steps:
  # ---------- Build Docker Image ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:$COMMIT_SHA",
        "-f", "myapp/Dockerfile",
        "myapp/"
      ]

  # ---------- Push to Artifact Registry ----------
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:$COMMIT_SHA"
      ]
  # ---------- Authenticate to GKE (Kubeconfig is written to /root/.kube/config) ----------
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        # 1. Authenticate to GKE
        "gcloud container clusters get-credentials gitlab-gke --zone asia-south1-c --project s-0-009988 && "

        # 2. Replace image tag inside YAML
        "sed -i \"s#IMAGE_PLACEHOLDER#asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app:${COMMIT_SHA}#g\" myapp/deployment.yaml && "

        # 3. Apply Kubernetes manifests
        "kubectl apply -f myapp/deployment.yaml --namespace default && "

        # 4. Wait for rollout
        "kubectl rollout status -f myapp/deployment.yaml --namespace default"
      ]
      
options:
  logging: CLOUD_LOGGING_ONLY
